name = "ImageInTerminal"
uuid = "d8c32880-2388-543b-8c61-d9f865259254"
version = "0.4.7"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
ImageBase = "c817782e-172a-44cc-b673-b171935fbb9e"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Crayons = "0.5, 1, 2, 3, 4"
ImageBase = "0.1"
ImageCore = "0.9"
Requires = "1"
julia = "1"

[extras]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageQualityIndexes = "2996bd0c-7a13-11e9-2da2-2f5ce47296a9"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["CoordinateTransformations", "ImageMagick", "ImageQualityIndexes", "ImageTransformations", "ReferenceTests", "Rotations", "SparseArrays", "OffsetArrays", "Pkg", "Test", "TestImages"]
